services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - flask

networks:
  app-network:
    driver: bridge